
server.port = 8090
spring.datasource.url=jdbc:postgresql://localhost:5433/tingeso_db
spring.datasource.username=tingeso_admin
spring.datasource.password=tingeso_password
spring.jpa.hibernate.ddl-auto=update

jwt.secret=colocolo
jwt.expiration=86400000
jwt.refreshExpiration=604800000



